In [1]:
import sys
sys.path.append('../src')

from linguistic_brain_toolkit.utilities import get_path
PATH = get_path(1)

In [4]:
from linguistic_brain_toolkit.nlp import apply_lemmatization_and_pos_tags

import sqlite3
import pandas as pd

pd.set_option('display.precision', 15)  # Establecer la precisión a 15 decimales

conn = sqlite3.connect(PATH + 'data/processed/transcriptions.db')
consulta_sql = "SELECT * FROM general"
df = pd.read_sql_query(consulta_sql, conn)
conn.close()

df.head()

             start             stop name   tier       source
0  0.0000000000000  0.0124716553288       phone  adollshouse
1  0.0124716553288  0.3816326530610   sp  phone  adollshouse
2  0.3816326530610  0.4215419501130  AO2  phone  adollshouse
3  0.4215419501130  0.4514739229020    L  phone  adollshouse
4  0.4514739229020  0.5213151927440    R  phone  adollshouse

In [6]:
# Preprocesing
df['name'] = df['name'].str.lower()
df['tier'].value_counts()

df_graphemic_transcrip = df.query("tier == 'word'").copy()

# NLP
df_processed = apply_lemmatization_and_pos_tags(df_graphemic_transcrip, 'name', 'large')
del df, df_graphemic_transcrip  # Delete dataframes to free memory
df_processed.head()

,start,stop,name,tier,source,lemmatized_text,pos_tags,pos_tag_1,pos_tag_2,pos_tag_3,pos_tag_4,pos_tag_5
5412,0.0000000000000,0.0124716553288,,word,adollshouse,,[],None,None,None,None,None
5413,0.0124716553288,0.3816326530610,sp,word,adollshouse,sp,[NOUN],NOUN,None,None,None,None
5414,0.3816326530610,0.6609977324260,alright,word,adollshouse,alright,[INTJ],INTJ,None,None,None,None
5415,0.6609977324260,0.9104308390020,thank,word,adollshouse,thank,[VERB],VERB,None,None,None,None
5416,0.9104308390020,1.0102040816300,you,word,adollshouse,you,[PRON],PRON,None,None,None,None